# Generated by Django 4.0.3 on 2022-03-22 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mywallz',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
